### ISSUE TITLE
Compatibility with the "Bottom Dollar Bounties" update

### ISSUE THREAD

**Issue by Michael21107** [TayMcKenzieNZ/mpstubcloths#1]
add `mp2024_01` like Alex did with the original resource

**Comment by TayMcKenzieNZ** [comment]
> add `mp2024_01` like Alex did with the original resource

To be honest, I don't really think this resource does anything, because I can't for the life of me figure out how to stream that meta file

**Comment by TayMcKenzieNZ** [comment]
I'll figure it out and give it a test and if I succeed then I'll update it. It looks like I need to add `PED_METADATA_FILE` to the fxmanifest.

**Comment by Michael21107** [comment]
copy

**Comment by TayMcKenzieNZ** [comment]
here you go @Michael21107, give this a try for me.

[mpstubcloths.zip](https://github.com/user-attachments/files/16022848/mpstubcloths.zip)

**Comment by Michael21107** [comment]
I dont mod fivem (besides installing SSLA) so id suggest you find someone more competent for that (I'd suggest a **pre-**release on this repo)

**Comment by TayMcKenzieNZ** [comment]
No problem. I don't bother with the releases section but everything seems to working fine for now and once FiveM updates to the latest DLC, it should be good to go.

**Comment by Michael21107** [comment]
gotcha, big up for making this
